//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopZvonochek.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneBuy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhoneBuy()
        {
            this.BackPhone = new HashSet<BackPhone>();
            this.Akt = new HashSet<Akt>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCleint { get; set; }
        public Nullable<int> IdAdmin { get; set; }
        public Nullable<int> IdPhone { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<bool> IsZayavka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackPhone> BackPhone { get; set; }
        public virtual Client Client { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Akt> Akt { get; set; }
    }
}
