//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopZvonochek.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> AmountMoney { get; set; }
        public string NameMasterskaya { get; set; }
    
        public virtual Masterskaya Masterskaya { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
