//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopZvonochek.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int Id { get; set; }
        public Nullable<int> IdPhone { get; set; }
        public Nullable<int> PhoneCount { get; set; }
    
        public virtual Phone Phone { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
